# Generated by Django 6.0.4 on 2026-05-05 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=255, null=True)),
                ('is_active', models.BooleanField()),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'db_table': 'product_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150)),
                ('file_type', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('external_url', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Arquivo do Produto',
                'verbose_name_plural': 'Arquivos do Produto',
                'db_table': 'product_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(max_length=255, upload_to='uploads/products/', verbose_name='Imagem')),
                ('alt_text', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=255, null=True)),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'db_table': 'product_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRoleContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='title', max_length=255, null=True)),
                ('content', models.TextField(blank=True, db_column='content', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
            ],
            options={
                'verbose_name': 'Permissão de Conteúdo',
                'verbose_name_plural': 'Permissões de Conteúdo',
                'db_table': 'product_role_contents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150, verbose_name='Nome do Produto')),
                ('slug', models.CharField(db_collation='Latin1_General_CI_AS', max_length=160, unique=True, verbose_name='Slug (URL)')),
                ('sku', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True, verbose_name='SKU/Código')),
                ('short_description', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=500, null=True, verbose_name='Descrição Curta')),
                ('full_description', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', null=True, verbose_name='Descrição Completa')),
                ('usage_tips', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', null=True, verbose_name='Dicas de Uso')),
                ('application_text', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', null=True, verbose_name='Aplicação')),
                ('technical_info', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', null=True, verbose_name='Informações Técnicas')),
                ('package_info', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=150, null=True, verbose_name='Embalagem')),
                ('weight_info', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True, verbose_name='Peso')),
                ('shelf_life_info', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True, verbose_name='Validade')),
                ('image_url', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/products/', verbose_name='Imagem Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Dica Vinculada',
                'verbose_name_plural': 'Dicas Vinculadas',
                'db_table': 'product_tips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Porção (ex: 50g)')),
                ('household_measure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Medida Caseira (ex: 1/2 xícara)')),
                ('portions_per_package', models.CharField(blank=True, max_length=50, null=True, verbose_name='Porções por Embalagem')),
                ('footer_note', models.TextField(blank=True, default='* Percentual de valores diários fornecidos pela porção.', null=True, verbose_name='Nota de Rodapé')),
                ('product', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='products.products', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Tabela Nutricional (Cabeçalho)',
                'db_table': 'product_nutrition',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductNutritionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Nutriente (ex: Carboidratos)')),
                ('value_100g', models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor por 100g')),
                ('value_serving', models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor por Porção')),
                ('vd_percentage', models.CharField(blank=True, max_length=10, null=True, verbose_name='% VD')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_rows', to='products.products', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Linha da Tabela Nutricional',
                'db_table': 'product_nutrition_rows',
                'ordering': ['sort_order'],
                'managed': True,
            },
        ),
    ]
