# Generated by Django 6.0.4 on 2026-05-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productnutrition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnutrition',
            name='col_4_label',
            field=models.CharField(blank=True, default='Extra 1', max_length=50, null=True, verbose_name='Título Coluna 4'),
        ),
        migrations.AddField(
            model_name='productnutrition',
            name='col_5_label',
            field=models.CharField(blank=True, default='Extra 2', max_length=50, null=True, verbose_name='Título Coluna 5'),
        ),
        migrations.AddField(
            model_name='productnutritionrow',
            name='value_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor Coluna 4'),
        ),
        migrations.AddField(
            model_name='productnutritionrow',
            name='value_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor Coluna 5'),
        ),
        migrations.AlterField(
            model_name='productnutrition',
            name='column_count',
            field=models.IntegerField(choices=[(1, '1 Coluna'), (2, '2 Colunas'), (3, '3 Colunas'), (4, '4 Colunas'), (5, '5 Colunas')], default=3, verbose_name='Número de Colunas no Site'),
        ),
        migrations.AlterField(
            model_name='productnutrition',
            name='product',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='products.products', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='productnutritionrow',
            name='value_100g',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor Coluna 1'),
        ),
        migrations.AlterField(
            model_name='productnutritionrow',
            name='value_serving',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor Coluna 2'),
        ),
        migrations.AlterField(
            model_name='productnutritionrow',
            name='vd_percentage',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Valor Coluna 3'),
        ),
    ]
