# Generated by Django 6.0.4 on 2026-04-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Marca')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link do Site')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Marca Parceira',
                'verbose_name_plural': 'Marcas Parceiras',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Excelência Técnica e Prática', max_length=200, verbose_name='Título Principal')),
                ('hero_subtitle', models.TextField(default='Bem-vindo à plataforma definitiva para profissionais de panificação, confeitaria e culinária.', verbose_name='Subtítulo')),
                ('about_title', models.CharField(default='Tradição e Qualidade desde o início', max_length=200, verbose_name='Título Quem Somos')),
                ('about_text1', models.TextField(verbose_name='Texto Quem Somos (Parágrafo 1)')),
                ('about_text2', models.TextField(blank=True, null=True, verbose_name='Texto Quem Somos (Parágrafo 2)')),
                ('about_stat1_title', models.CharField(default='+60 Anos', max_length=50, verbose_name='Estatística 1 - Título')),
                ('about_stat1_desc', models.CharField(default='de tradição no mercado', max_length=100, verbose_name='Estatística 1 - Descrição')),
                ('about_stat2_title', models.CharField(default='Alta Tecnologia', max_length=50, verbose_name='Estatística 2 - Título')),
                ('about_stat2_desc', models.CharField(default='nas unidades produtivas', max_length=100, verbose_name='Estatística 2 - Descrição')),
                ('where_to_buy_title', models.CharField(default='Onde Comprar', max_length=200, verbose_name='Título Onde Comprar')),
                ('where_to_buy_text', models.TextField(verbose_name='Texto Onde Comprar')),
                ('where_to_buy_phone', models.CharField(default='0800 000 0000', max_length=50, verbose_name='Telefone de Vendas')),
                ('where_to_buy_hours', models.CharField(default='Segunda a Sexta, das 08h às 18h', max_length=100, verbose_name='Horário de Atendimento')),
            ],
            options={
                'verbose_name': 'Configuração da Home',
                'verbose_name_plural': 'Configurações da Home',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição Curta')),
                ('image_url', models.URLField(blank=True, help_text='Link para a imagem da dica', null=True, verbose_name='URL da Imagem')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link para Leitura Completa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dica de Uso',
                'verbose_name_plural': 'Dicas de Uso',
                'ordering': ['-created_at'],
            },
        ),
    ]
