# Generated by Django 6.0.4 on 2026-05-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150, verbose_name='Título do Arquivo')),
                ('sort_order', models.IntegerField(verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Arquivo do Treinamento',
                'verbose_name_plural': 'Arquivos do Treinamento',
                'db_table': 'restricted_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestrictedMaterialRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'restricted_material_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestrictedMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150, verbose_name='Título')),
                ('description', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', null=True, verbose_name='Descrição')),
                ('content', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', null=True, verbose_name='Conteúdo Adicional')),
                ('audience_type', models.CharField(db_collation='Latin1_General_CI_AS', max_length=30, verbose_name='Tipo de Público')),
                ('is_active', models.BooleanField(verbose_name='Ativo')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Material de Treinamento',
                'verbose_name_plural': 'Materiais de Treinamento',
                'db_table': 'restricted_materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestrictedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título do Vídeo')),
                ('video_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Externa (opcional)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='training/videos/', verbose_name='Arquivo de Vídeo (Upload)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restricted_material', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='training.restrictedmaterials', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Vídeo do Treinamento',
                'verbose_name_plural': 'Vídeos do Treinamento',
                'db_table': 'restricted_videos',
                'managed': True,
            },
        ),
    ]
