# Generated by Django 6.0.4 on 2026-05-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restrictedfiles',
            options={'managed': True, 'verbose_name': 'Arquivo do Treinamento', 'verbose_name_plural': 'Arquivos do Treinamento'},
        ),
    ]
