# Generated by Django 6.0.4 on 2026-04-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150, unique=True)),
                ('password_hash', models.CharField(db_collation='Latin1_General_CI_AS', max_length=255)),
                ('phone', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=30, null=True)),
                ('document_number', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=30, null=True)),
                ('user_type', models.CharField(db_collation='Latin1_General_CI_AS', max_length=30)),
                ('status', models.CharField(db_collation='Latin1_General_CI_AS', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('password_reset_token', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=255, null=True)),
                ('password_reset_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
